name: Coletar noticias

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  coletar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install feedparser

      - name: Executar coletor
        run: python coletor.py
